version: "3.9"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/volumes/mysql/data:/var/lib/mysql
      - ~/volumes/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    env_file:
      - .env
